name: 'Auto commit and push'
description: 'after autogeneration workflow should commit and push'
inputs:
  GITHUB_TOKEN:
    description: "Action token"
    required: true
  FOLDER_TO_COMMIT:
    description: "delete it"
    required: true
  FILE_TO_COMMIT:
    description: "Target file which will be committed"
    required: true
  DESTINATION_BRANCH:
    description: "Target branch"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
